package com.keypoint.keypointtravel.global.enumType.notification;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum PushNotificationMsg {
    RECEIPT_REGISTER(
        PushNotificationType.RECEIPT_REGISTER,
        "pushNotification.receiptRegister_title",
        "pushNotification.receiptRegister_content"
    ),
    FRIEND_INVITE_1(
        PushNotificationType.FRIEND_INVITE,
        "pushNotification.friendInvite1_title",
        "pushNotification.friendInvite1_content"
    ),
    FRIEND_INVITE_2(
        PushNotificationType.FRIEND_INVITE,
        "pushNotification.friendInvite2_title",
        "pushNotification.friendInvite2_content"
    ),
    FRIEND_INVITE_3(
        PushNotificationType.FRIEND_INVITE,
        "pushNotification.friendInvite3_title",
        "pushNotification.friendInvite3_content"
    ),
    FRIEND_INVITE_4(
        PushNotificationType.FRIEND_INVITE,
        "pushNotification.friendInvite4_title",
        "pushNotification.friendInvite4_content"
    ),
    FRIEND_INVITE_5(
        PushNotificationType.FRIEND_INVITE,
        "pushNotification.friendInvite5_title",
        "pushNotification.friendInvite5_content"
    ),
    CAMPAIGN_D_DAY_1(
        PushNotificationType.CAMPAIGN_D_DAY,
        "pushNotification.campaignDDay1_title",
        "pushNotification.campaignDDay1_content"
    ),
    CAMPAIGN_D_DAY_2(
        PushNotificationType.CAMPAIGN_D_DAY,
        "pushNotification.campaignDDay2_title",
        "pushNotification.campaignDDay2_content"
    ),
    CAMPAIGN_D_DAY_3(
        PushNotificationType.CAMPAIGN_D_DAY,
        "pushNotification.campaignDDay3_title",
        "pushNotification.campaignDDay3_content"
    ),
    CAMPAIGN_D_DAY_4(
        PushNotificationType.CAMPAIGN_D_DAY,
        "pushNotification.campaignDDay4_title",
        "pushNotification.campaignDDay4_content"
    ),
    CAMPAIGN_D_DAY_5(
        PushNotificationType.CAMPAIGN_D_DAY,
        "pushNotification.campaignDDay5_title",
        "pushNotification.campaignDDay5_content"
    ),
    CAMPAIGN_INVITE(
        PushNotificationType.CAMPAIGN_INVITE,
        "pushNotification.campaignInvite_title",
        "pushNotification.campaignInvite_content"
    ),
    CAMPAIGN_ACCEPT_INVITER(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITER,
        "pushNotification.campaignAcceptInviter_title",
        "pushNotification.campaignAcceptInviter_content"
    ),

    CAMPAIGN_ACCEPT_INVITEE(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.campaignAcceptInvitee_title",
        "pushNotification.campaignAcceptInvitee_content"
    ),
    CAMPAIGN_NO_EXPENSE_D1(
        PushNotificationType.CAMPAIGN_NO_EXPENSE_D1,
        "pushNotification.campaignNoExpenseD1_title",
        "pushNotification.campaignNoExpenseD1_content"
    ),
    CAMPAIGN_END(
        PushNotificationType.CAMPAIGN_END,
        "pushNotification.campaignEnd_title",
        "pushNotification.campaignEnd_content"
    ),
    CAMPAIGN_JOIN_REQUEST(
        PushNotificationType.CAMPAIGN_JOIN_REQUEST,
        "pushNotification.campaignJoinRequest_title",
        "pushNotification.campaignJoinRequest_content"
    ),
    PAYMENT_COMPLETION(
        PushNotificationType.PAYMENT_COMPLETION,
        "pushNotification.paymentCompleted_title",
        "pushNotification.paymentCompleted_content"
    ),
    FRIEND_ADDED(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.friendAdded_title",
        "pushNotification.friendAdded_content"
    ),
    FRIEND_ACCEPTED_RECEIVER(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.friendAcceptedReceiver_title",
        "pushNotification.friendAcceptedReceiver_content"
    ),
    FRIEND_ACCEPTED_SENDER(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.friendAcceptedSender_title",
        "pushNotification.friendAcceptedSender_content"
    ),
    INQUIRY_RESPONSE_COMPLETED(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.inquiryResponseCompleted_title",
        "pushNotification.inquiryResponseCompleted_content"
    ),
    CAMPAIGN_D60_PASSED_1(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.campaignD60Passed1_title",
        "pushNotification.campaignD60Passed1_content"),
    CAMPAIGN_D60_PASSED_2(
        PushNotificationType.CAMPAIGN_ACCEPT_INVITEE,
        "pushNotification.campaignD60Passed2_title",
        "pushNotification.campaignD60Passed2_content"
    );

    private final PushNotificationType type;
    private final String titleLangCode;
    private final String contentLangCode;
}
