spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: study.lchy@gmail.com
    password: ybuqosaesdthcgsb
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true