key:
  aes:
    secret-key: 36114567890121556789012326673001
  azure:
    key1: a4471a1b0bbf48908b9714eb7ff430ee
    key2: 06d02571cc2c4b2a9f49fec2352b8c43
    local: koreacentral
    endpoint: https://keypoint-travel-api.cognitiveservices.azure.com/
    api-version: 2023-07-31
  service:
    key: 3F2B7A98C4D1E3F5A6
  jwt:
    secret-key: 6B64DCA4E72F58EDIKU9AAB215FE76B64DCA4E72F58EDIKU9AAB215FE7
    accesstoken-validity-in-min: 60
    refreshtoken-validity-in-min: 600
  tourApi:
    key: VqOVEqFvT2RkIyzj2jxy5SwBAQmfSbpulCzRcS%2FcKZJ1Ir8OW9rYB4bNCkIy1nJ7xApQ9tOm8mpVi%2B6N2EKgCA%3D%3D
  exchange-rate:
    key: 30Qd7bHX48NBAUKS0JozEHuhrDTJNQXq
spring:
  security:
    oauth2:
      authorizedRedirectUri: /sign-in
      client:
        provider:
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
            tokenUri: https://www.googleapis.com/oauth2/v4/token
        registration:
          apple:
            clientId: com.keypoint.keytrip
            clientSecret: AuthKey_ANS9W23GB3.p8
            redirect-uri: https://back-dev.keypointtravel.com/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - email
          google:
            client-id: 308423055794-7qq0j6f3jghc6gvpmqg84nf5036ube21.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
apple:
  teamId: N95583Y4V3
  keyId: ANS9W23GB3
  keyPath: AuthKey_ANS9W23GB3.p8
cloud:
  aws:
    credentials:
      access-key: AKIA47CRUIKOVUZGUPEK
      secret-access-key: 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
    s3:
      bucket: backend-keypoint-travel
    region:
      static: ap-northeast-2
    stack:
      auto: false