spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  profiles:
    default: local
    group:
      local: "local, local-key, mail"
      dev: "dev, key, mail"
logging:
  level:
    com.keypoint.keypointtravel: DEBUG