version: "3.8"

services:
  web:
    container_name: web
    image: lchy0413/keypoint-travel-dev
    expose:
      - 8080
    ports:
      - 8080:8080
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  redis:
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /data/redis:/data
      - /script/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always