-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaRfCYYWNWTPEdUIs
B4Bv2DeCyy1pASuSYTSnI+O7kAugCgYIKoZIzj0DAQehRANCAASL0Am/UFYs5N5V
DXrJUeBC2HX/ZtSR+LLmrRkDxWxOVfEVpb9XhwUWBHpCAnPUBl3uud9dMmcNRMkY
+pGNZrdO
-----END PRIVATE KEY-----