-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+ffVMW1+ubRnrbyT
qvtOdvvGQdmYmRe98FOrRW6I5qKgCgYIKoZIzj0DAQehRANCAASbFkmL/SeLsfm3
MpPvlhccO+Kpo1qBsW32CECG75GRgRfR/kgKyvttInHiXqHGDiWZsvvDhD809uTn
pAjMTa1w
-----END PRIVATE KEY-----